upstream asyncgram_auth {
    server 127.0.0.1:8001;
}

upstream asyncgram_chat {
    server 127.0.0.1:8002;
}

upstream asyncgram_ws {
    server 127.0.0.1:8003;
}

upstream asyncgram_media {
    server 127.0.0.1:8004;
}

upstream asyncgram_admin {
    server 127.0.0.1:8005;
}

server {
    listen 8080;
    server_name _;
    client_max_body_size 12m;

    location /auth/ {
        proxy_pass http://asyncgram_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /users/me {
        proxy_pass http://asyncgram_auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /chats/ {
        proxy_pass http://asyncgram_chat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /messages {
        proxy_pass http://asyncgram_chat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /users/search {
        proxy_pass http://asyncgram_chat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /upload {
        proxy_pass http://asyncgram_media;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 12m;
    }

    location /uploads/ {
        proxy_pass http://asyncgram_media;
        proxy_set_header Host $host;
    }

    location /admin/ {
        proxy_pass http://asyncgram_admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/chat {
        proxy_pass http://asyncgram_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }

    location /health {
        return 200 'gateway ok';
        add_header Content-Type text/plain;
    }
}
